version: '3.7'
services:
  puppeteer:
    image: browserless/chrome
    command: ["google-chrome-stable", "--no-sandbox", "--disable-dev-shm-usage", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - "9222:9222"
