version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.23.0
    restart: on-failure:0
    ports:
     - 8088:8080
     - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: text2vec-transformers
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:baai-bge-base-en-v1.5-onnx
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
networks:
  weaviate_network:
    driver: bridge
